equipments/urls.py
from django.urls import path
from .views import input_equipment_view, home_view, home_view_after_input

app_name = 'equipments'

urlpatterns = [
    path('input', input_equipment_view, name="input"),
    path('home', home_view, name="home"),
    path('home_after_input', home_view_after_input, name="home_after_input"),
    path('', home_view, name="home"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from equipments.views import home_view,home_view_after_input, popup_temperature_view, popup_overdue_view
from equipments.views import edit_equipment_view, edit_last_equipment_view, home_view_for_correction
from equipments.views import home_for_search_view, popup_overdue_and_temperature_view
from django.contrib.auth import views as auth_views
from a02_account.views import registration_view, logout_view, login_view, account_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view,{}, name="home"),
    path('home_for_correction', home_view_for_correction, {}, name="home_for_correction"),
    path('home_for_search', home_for_search_view, {}, name="home_for_search"),


    path('equipments/', include('equipments.urls', 'equipments')),
    path('home_after_input', home_view_after_input, name="home_after_input"),
    path('pop_temperature', popup_temperature_view, name="pop_temperature"),
    path('pop_overdue', popup_overdue_view, name="pop_overdue"),
    path('pop_overdue_temperature', popup_overdue_and_temperature_view, name="pop_overdue_temperature"),

    path('edit_equipment/<int:equipment_id>/', edit_equipment_view, name='edit_equipment'),
    path('edit_last_equipment/', edit_last_equipment_view, name='edit_last_equipment'),


    path('register/', registration_view, name='register'),
    path('logout/', logout_view, name='logout'),
    path('login/', login_view, name='login'),
    path('account/', account_view, name='account'),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
         name='password_change'),

    path('password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),
]

templates/snippets/base_css.html
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<style type="text/css">
    body{
        background-color: #f2f2f2;
        padding-top: 0px
    }
    .main{
        min-height: 100vh;
        height: 100%;
    }
</style>

templates/snippets/footer.html
<hr>
<p>Zimmerbiomet Equipment usage log rev.2023</p>



templates/snippets/header.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

   <a href="/" class="d-flex align-items-center link-body-emphasis text-decoration-none">
        {% if request.user.is_authenticated %}
            <span class="fs-5">Hello, {{request.user.username}}</span>
        {% else %}
            <span class="fs-5">Welcome</span>
        {% endif %}
    </a>
<!--<a class="me-3 py-2 link-body-emphasis text-decoration-none" href="/">All List</a>-->
<a class="me-3 py-2 link-body-emphasis" href="/">All List</a>
<a class="me-3 py-2 link-body-emphasis" href="/home_for_search">Search</a>


    <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
        {% if request.user.is_authenticated %}
            <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'account' %}">Account</a>
            <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'logout' %}">Logout</a>
            <a class="me-3 py-2 " href="{% url 'equipments:input' %}">Input</a>
            {% if request.user.is_superuser %}
                <a class="me-3 py-2" href="{% url 'home_for_correction' %}"><i>Correction</i></a>
            {% endif %}
        {% else %}
            <a class="me-3 py-2 " href="{% url 'login' %}">Login</a>
        {% endif %}
    </nav>
<hr>